/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel-plugin for production.
 */
const documents = {
    "\n  query getProvincesAdminAutoComplete(\n    $getProvincesAdminArgs: GetProvincesAdminArgsGQL!\n  ) {\n    getProvincesAdmin(\n      getProvincesAdminArgs: $getProvincesAdminArgs\n      paginationArgs: { limit: 30, page: 1 }\n    ) {\n      edges {\n        id\n        name\n      }\n    }\n  }\n": types.GetProvincesAdminAutoCompleteDocument,
    "\n  mutation removeImageAdmin($removeImageAdmin: RemoveImageAdminInputsGQL!) {\n    removeImageAdmin(removeImageAdmin: $removeImageAdmin) {\n      id\n      filename\n    }\n  }\n": types.RemoveImageAdminDocument,
    "\n  mutation uploadFile($file: Upload!) {\n    uploadFile(file: $file) {\n      id\n      path\n      filename\n    }\n  }\n": types.UploadFileDocument,
    "\n  query getFileByIdAdmin($fileId: String!) {\n    getFileByIdAdmin(fileId: $fileId) {\n      id\n      filename\n    }\n  }\n": types.GetFileByIdAdminDocument,
    "\n  query meAdmin {\n    meAdmin {\n      id\n      lastName\n      firstName\n      createdAt\n      roles\n      username\n    }\n  }\n": types.MeAdminDocument,
    "\n  mutation updateCustomerActionAdminInputs(\n    $updateCustomerActionAdminInputs: UpdateCustomerActionAdminInputsGQL!\n  ) {\n    updateCustomerActionAdmin(\n      updateCustomerActionAdminInputs: $updateCustomerActionAdminInputs\n    ) {\n      id\n      text\n      customerId\n      userId\n    }\n  }\n": types.UpdateCustomerActionAdminInputsDocument,
    "\n  mutation addFileToCustomerActionAdmin(\n    $addFileToCustomerActionAdmin: AddFileToCustomerActionAdminInputsGQL!\n  ) {\n    addFileToCustomerActionAdmin(\n      addFileToCustomerActionAdmin: $addFileToCustomerActionAdmin\n    ) {\n      id\n    }\n  }\n": types.AddFileToCustomerActionAdminDocument,
    "\n  query getCustomerActionByIdAdmin($customerActionId: String!) {\n    getCustomerActionByIdAdmin(customerActionId: $customerActionId) {\n      id\n      text\n      customerId\n      customer {\n        email\n        jobTitle\n        phone\n        officePhone\n      }\n      userId\n      user {\n        id\n        firstName\n        username\n      }\n      fileUses {\n        id\n        file {\n          id\n          filename\n        }\n      }\n    }\n  }\n": types.GetCustomerActionByIdAdminDocument,
    "\n  query getCustomerActionsAdmin(\n    $getCustomerActionsAdminArgs: GetCustomerActionsAdminArgsGQL!\n    $paginationArgs: PaginationArgsGQL!\n  ) {\n    getCustomerActionsAdmin(\n      getCustomerActionsAdminArgs: $getCustomerActionsAdminArgs\n      paginationArgs: $paginationArgs\n    ) {\n      pageInfo {\n        totalEdges\n        edgeCount\n        edgesPerPage\n        currentPage\n        totalPages\n      }\n      edges {\n        id\n        text\n        customer {\n          email\n          jobTitle\n          phone\n          officePhone\n        }\n        userId\n        user {\n          id\n          firstName\n          lastName\n          username\n        }\n        fileUses {\n          id\n          file {\n            id\n            filename\n          }\n        }\n      }\n    }\n  }\n": types.GetCustomerActionsAdminDocument,
    "\n  mutation createCustomerActionAdminInputs(\n    $createCustomerActionAdminInputs: CreateCustomerActionAdminInputsGQL!\n  ) {\n    createCustomerActionAdmin(\n      createCustomerActionAdminInputs: $createCustomerActionAdminInputs\n    ) {\n      id\n      text\n      customerId\n      userId\n    }\n  }\n": types.CreateCustomerActionAdminInputsDocument,
    "\n  query getCustomerByIdAdmin($customerId: String!) {\n    getCustomerByIdAdmin(customerId: $customerId) {\n      id\n      firstName\n      lastName\n      email\n      jobTitle\n      phone\n      officePhone\n      isActive\n      cityId\n      city {\n        name\n        id\n        province {\n          id\n          name\n        }\n      }\n    }\n  }\n": types.GetCustomerByIdAdminDocument,
    "\n  query getCustomersAdmin(\n    $getCustomersAdminArgs: GetCustomersAdminArgsGQL!\n    $paginationArgs: PaginationArgsGQL!\n  ) {\n    getCustomersAdmin(\n      getCustomersAdminArgs: $getCustomersAdminArgs\n      paginationArgs: $paginationArgs\n    ) {\n      pageInfo {\n        totalEdges\n        edgeCount\n        edgesPerPage\n        currentPage\n        totalPages\n      }\n      edges {\n        id\n        firstName\n        lastName\n        email\n        jobTitle\n        phone\n        officePhone\n        isActive\n        cityId\n        city {\n          id\n          name\n          province {\n            name\n            id\n          }\n        }\n      }\n    }\n  }\n": types.GetCustomersAdminDocument,
    "\n  query loginAdmin($loginAdminInputs: LoginAdminInputsGQL!) {\n    loginAdmin(loginAdminInputs: $loginAdminInputs) {\n      id\n      lastName\n      firstName\n      createdAt\n      roles\n      username\n    }\n  }\n": types.LoginAdminDocument,
    "\n  query logoutAdmin {\n    logoutAdmin {\n      id\n    }\n  }\n": types.LogoutAdminDocument,
    "\n  query getMessageByIdAdmin($messageId: String!) {\n    getMessageByIdAdmin(messageId: $messageId) {\n      id\n      text\n      count\n      createdAt\n      updatedAt\n      deletedAt\n      isActive\n      isSubmited\n      userId\n      user {\n        id\n        username\n        firstName\n        lastName\n      }\n      customerMessages {\n        id\n        customer {\n          id\n          email\n          jobTitle\n          firstName\n          lastName\n          email\n          phone\n          officePhone\n          isActive\n          city {\n            id\n            name\n            province {\n              id\n              name\n            }\n          }\n        }\n      }\n    }\n  }\n": types.GetMessageByIdAdminDocument,
    "\n  query getMessagesAdmin(\n    $getMessagesAdminArgs: GetMessagesAdminArgsGQL!\n    $paginationArgs: PaginationArgsGQL!\n  ) {\n    getMessagesAdmin(\n      getMessagesAdminArgs: $getMessagesAdminArgs\n      paginationArgs: $paginationArgs\n    ) {\n      pageInfo {\n        totalEdges\n        edgeCount\n        edgesPerPage\n        currentPage\n        totalPages\n      }\n      edges {\n        id\n        text\n        count\n        createdAt\n        updatedAt\n        deletedAt\n        isActive\n        isSubmited\n        userId\n        user {\n          id\n          username\n          firstName\n          lastName\n        }\n        customerMessages {\n          id\n          customer {\n            id\n            email\n            jobTitle\n            firstName\n            lastName\n            email\n            phone\n            officePhone\n          }\n        }\n      }\n    }\n  }\n": types.GetMessagesAdminDocument,
    "\n  mutation updateProducerActionAdminInputs(\n    $updateProducerActionAdminInputs: UpdateProducerActionAdminInputsGQL!\n  ) {\n    updateProducerActionAdmin(\n      updateProducerActionAdminInputs: $updateProducerActionAdminInputs\n    ) {\n      id\n      text\n      producerId\n      userId\n    }\n  }\n": types.UpdateProducerActionAdminInputsDocument,
    "\n  mutation addFileToProducerActionAdmin(\n    $addFileToProducerActionAdmin: AddFileToProducerActionAdminInputsGQL!\n  ) {\n    addFileToProducerActionAdmin(\n      addFileToProducerActionAdmin: $addFileToProducerActionAdmin\n    ) {\n      id\n    }\n  }\n": types.AddFileToProducerActionAdminDocument,
    "\n  query getProducerActionByIdAdmin($producerActionId: String!) {\n    getProducerActionByIdAdmin(producerActionId: $producerActionId) {\n      id\n      text\n      producerId\n      producer {\n        id\n        name\n        phone\n        email\n        description\n        address\n        isActive\n      }\n      userId\n      user {\n        id\n        firstName\n        username\n        email\n        lastName\n      }\n      fileUses {\n        id\n        file {\n          id\n          filename\n          path\n          isUsed\n          size\n        }\n      }\n    }\n  }\n": types.GetProducerActionByIdAdminDocument,
    "\n  query getProducerActionsAdmin(\n    $getProducerActionsAdminArgs: GetProducerActionsAdminArgsGQL!\n    $paginationArgs: PaginationArgsGQL!\n  ) {\n    getProducerActionsAdmin(\n      getProducerActionsAdminArgs: $getProducerActionsAdminArgs\n      paginationArgs: $paginationArgs\n    ) {\n      pageInfo {\n        totalEdges\n        edgeCount\n        edgesPerPage\n        currentPage\n        totalPages\n      }\n      edges {\n        id\n        text\n        producer {\n          id\n          name\n          phone\n          email\n          description\n          address\n        }\n        userId\n        user {\n          id\n          firstName\n          username\n          lastName\n        }\n        fileUses {\n          id\n        }\n      }\n    }\n  }\n": types.GetProducerActionsAdminDocument,
    "\n  query getProducerAgentByIdAdmin($producerAgentId: String!) {\n    getProducerAgentByIdAdmin(producerAgentId: $producerAgentId) {\n      id\n      createdAt\n      firstName\n      lastName\n      email\n      phone\n      description\n      isActive\n      producer {\n        id\n        name\n        phone\n        email\n        cityId\n        city {\n          id\n          name\n          province {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n": types.GetProducerAgentByIdAdminDocument,
    "\n  query getProducerAgentsAdmin(\n    $getProducerAgentsAdminArgs: GetProducerAgentsAdminArgsGQL!\n    $paginationArgs: PaginationArgsGQL!\n  ) {\n    getProducerAgentsAdmin(\n      getProducerAgentsAdminArgs: $getProducerAgentsAdminArgs\n      paginationArgs: $paginationArgs\n    ) {\n      pageInfo {\n        totalEdges\n        edgeCount\n        edgesPerPage\n        currentPage\n        totalPages\n      }\n      edges {\n        id\n        createdAt\n        firstName\n        lastName\n        email\n        phone\n        description\n        isActive\n        producer {\n          id\n          name\n          phone\n          email\n          cityId\n          city {\n            id\n            name\n            province {\n              id\n              name\n            }\n          }\n        }\n      }\n    }\n  }\n": types.GetProducerAgentsAdminDocument,
    "\n  mutation createProducerActionAdminInputs(\n    $createProducerActionAdminInputs: CreateProducerActionAdminInputsGQL!\n  ) {\n    createProducerActionAdmin(\n      createProducerActionAdminInputs: $createProducerActionAdminInputs\n    ) {\n      id\n      text\n      producerId\n      userId\n    }\n  }\n": types.CreateProducerActionAdminInputsDocument,
    "\n  query getProducerByIdAdmin($producerId: String!) {\n    getProducerByIdAdmin(producerId: $producerId) {\n      id\n      name\n      phone\n      email\n      description\n      address\n      isActive\n      cityId\n      city {\n        id\n        name\n        province {\n          name\n          id\n        }\n      }\n    }\n  }\n": types.GetProducerByIdAdminDocument,
    "\n  query getProducersAdmin(\n    $getProducersAdminArgs: GetProducersAdminArgsGQL!\n    $paginationArgs: PaginationArgsGQL!\n  ) {\n    getProducersAdmin(\n      getProducersAdminArgs: $getProducersAdminArgs\n      paginationArgs: $paginationArgs\n    ) {\n      pageInfo {\n        totalEdges\n        edgeCount\n        edgesPerPage\n        currentPage\n        totalPages\n      }\n      edges {\n        id\n        email\n        name\n        description\n        address\n        phone\n        isActive\n        cityId\n        city {\n          id\n          name\n          province {\n            name\n            id\n          }\n        }\n      }\n    }\n  }\n": types.GetProducersAdminDocument,
    "\n  query getProductByIdAdmin($productId: String!) {\n    getProductByIdAdmin(productId: $productId) {\n      id\n      name\n      slug\n      isActive\n      text\n      productColors {\n        id\n        colorId\n        color {\n          id\n          value\n          name\n        }\n      }\n      productReviews {\n        id\n        reviewer\n        text\n      }\n      productCategories {\n        id\n        categoryId\n        category {\n          id\n          name\n        }\n      }\n      productProperties {\n        id\n        value\n        property {\n          id\n          name\n          unit\n          isActive\n        }\n      }\n      fileUses {\n        file {\n          id\n          filename\n          path\n        }\n      }\n    }\n  }\n": types.GetProductByIdAdminDocument,
    "\n  query getProductsAdmin(\n    $getProductsAdminArgs: GetProductsAdminArgsGQL!\n    $paginationArgs: PaginationArgsGQL!\n  ) {\n    getProductsAdmin(\n      getProductsAdminArgs: $getProductsAdminArgs\n      paginationArgs: $paginationArgs\n    ) {\n      pageInfo {\n        totalEdges\n        edgeCount\n        edgesPerPage\n        currentPage\n        totalPages\n      }\n      edges {\n        slug\n        id\n        name\n        isActive\n        createdAt\n        updatedAt\n        deletedAt\n        text\n        productProperties {\n          id\n          value\n          property {\n            name\n            unit\n          }\n        }\n        fileUses {\n          id\n          status\n          type\n          isPublic\n          file {\n            filename\n            size\n            id\n          }\n        }\n      }\n    }\n  }\n": types.GetProductsAdminDocument,
    "\n  mutation updateTransporterActionAdminInputs(\n    $updateTransporterActionAdminInputs: UpdateTransporterActionAdminInputsGQL!\n  ) {\n    updateTransporterActionAdmin(\n      updateTransporterActionAdminInputs: $updateTransporterActionAdminInputs\n    ) {\n      id\n      text\n      transporterId\n      userId\n    }\n  }\n": types.UpdateTransporterActionAdminInputsDocument,
    "\n  mutation addFileToTransporterActionAdmin(\n    $addFileToTransporterActionAdmin: AddFileToTransporterActionAdminInputsGQL!\n  ) {\n    addFileToTransporterActionAdmin(\n      addFileToTransporterActionAdmin: $addFileToTransporterActionAdmin\n    ) {\n      id\n    }\n  }\n": types.AddFileToTransporterActionAdminDocument,
    "\n  query getTransporterActionByIdAdmin($transporterActionId: String!) {\n    getTransporterActionByIdAdmin(transporterActionId: $transporterActionId) {\n      id\n      text\n      transporterId\n      transporter {\n        id\n        name\n        phone\n        email\n        description\n        address\n        isActive\n      }\n      userId\n      user {\n        id\n        firstName\n        username\n        email\n        lastName\n      }\n      fileUses {\n        id\n        file {\n          id\n          filename\n          path\n          isUsed\n          size\n        }\n      }\n    }\n  }\n": types.GetTransporterActionByIdAdminDocument,
    "\n  query getTransporterActionsAdmin(\n    $getTransporterActionsAdminArgs: GetTransporterActionsAdminArgsGQL!\n    $paginationArgs: PaginationArgsGQL!\n  ) {\n    getTransporterActionsAdmin(\n      getTransporterActionsAdminArgs: $getTransporterActionsAdminArgs\n      paginationArgs: $paginationArgs\n    ) {\n      pageInfo {\n        totalEdges\n        edgeCount\n        edgesPerPage\n        currentPage\n        totalPages\n      }\n      edges {\n        id\n        text\n        transporter {\n          id\n          name\n          phone\n          email\n          description\n          address\n        }\n        userId\n        user {\n          id\n          firstName\n          username\n          lastName\n        }\n        fileUses {\n          id\n        }\n      }\n    }\n  }\n": types.GetTransporterActionsAdminDocument,
    "\n  query getTransporterAgentByIdAdmin($transporterAgentId: String!) {\n    getTransporterAgentByIdAdmin(transporterAgentId: $transporterAgentId) {\n      id\n      createdAt\n      firstName\n      lastName\n      email\n      phone\n      description\n      isActive\n      transporter {\n        id\n        name\n        phone\n        email\n        cityId\n        city {\n          id\n          name\n          province {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n": types.GetTransporterAgentByIdAdminDocument,
    "\n  query getTransporterAgentsAdmin(\n    $getTransporterAgentsAdminArgs: GetTransporterAgentsAdminArgsGQL!\n    $paginationArgs: PaginationArgsGQL!\n  ) {\n    getTransporterAgentsAdmin(\n      getTransporterAgentsAdminArgs: $getTransporterAgentsAdminArgs\n      paginationArgs: $paginationArgs\n    ) {\n      pageInfo {\n        totalEdges\n        edgeCount\n        edgesPerPage\n        currentPage\n        totalPages\n      }\n      edges {\n        id\n        createdAt\n        firstName\n        lastName\n        email\n        phone\n        description\n        isActive\n        transporter {\n          id\n          name\n          phone\n          email\n          cityId\n          city {\n            id\n            name\n            province {\n              id\n              name\n            }\n          }\n        }\n      }\n    }\n  }\n": types.GetTransporterAgentsAdminDocument,
    "\n  mutation createTransporterActionAdminInputs(\n    $createTransporterActionAdminInputs: CreateTransporterActionAdminInputsGQL!\n  ) {\n    createTransporterActionAdmin(\n      createTransporterActionAdminInputs: $createTransporterActionAdminInputs\n    ) {\n      id\n      text\n      transporterId\n      userId\n    }\n  }\n": types.CreateTransporterActionAdminInputsDocument,
    "\n  query getTransporterByIdAdmin($transporterId: String!) {\n    getTransporterByIdAdmin(transporterId: $transporterId) {\n      id\n      name\n      phone\n      email\n      description\n      address\n      isActive\n      cityId\n      city {\n        id\n        name\n        province {\n          name\n          id\n        }\n      }\n    }\n  }\n": types.GetTransporterByIdAdminDocument,
    "\n  query getTransportersAdmin(\n    $getTransportersAdminArgs: GetTransportersAdminArgsGQL!\n    $paginationArgs: PaginationArgsGQL!\n  ) {\n    getTransportersAdmin(\n      getTransportersAdminArgs: $getTransportersAdminArgs\n      paginationArgs: $paginationArgs\n    ) {\n      pageInfo {\n        totalEdges\n        edgeCount\n        edgesPerPage\n        currentPage\n        totalPages\n      }\n      edges {\n        id\n        email\n        name\n        description\n        address\n        phone\n        isActive\n        cityId\n        city {\n          id\n          name\n          province {\n            name\n            id\n          }\n        }\n      }\n    }\n  }\n": types.GetTransportersAdminDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = gql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query getProvincesAdminAutoComplete(\n    $getProvincesAdminArgs: GetProvincesAdminArgsGQL!\n  ) {\n    getProvincesAdmin(\n      getProvincesAdminArgs: $getProvincesAdminArgs\n      paginationArgs: { limit: 30, page: 1 }\n    ) {\n      edges {\n        id\n        name\n      }\n    }\n  }\n"): (typeof documents)["\n  query getProvincesAdminAutoComplete(\n    $getProvincesAdminArgs: GetProvincesAdminArgsGQL!\n  ) {\n    getProvincesAdmin(\n      getProvincesAdminArgs: $getProvincesAdminArgs\n      paginationArgs: { limit: 30, page: 1 }\n    ) {\n      edges {\n        id\n        name\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation removeImageAdmin($removeImageAdmin: RemoveImageAdminInputsGQL!) {\n    removeImageAdmin(removeImageAdmin: $removeImageAdmin) {\n      id\n      filename\n    }\n  }\n"): (typeof documents)["\n  mutation removeImageAdmin($removeImageAdmin: RemoveImageAdminInputsGQL!) {\n    removeImageAdmin(removeImageAdmin: $removeImageAdmin) {\n      id\n      filename\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation uploadFile($file: Upload!) {\n    uploadFile(file: $file) {\n      id\n      path\n      filename\n    }\n  }\n"): (typeof documents)["\n  mutation uploadFile($file: Upload!) {\n    uploadFile(file: $file) {\n      id\n      path\n      filename\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query getFileByIdAdmin($fileId: String!) {\n    getFileByIdAdmin(fileId: $fileId) {\n      id\n      filename\n    }\n  }\n"): (typeof documents)["\n  query getFileByIdAdmin($fileId: String!) {\n    getFileByIdAdmin(fileId: $fileId) {\n      id\n      filename\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query meAdmin {\n    meAdmin {\n      id\n      lastName\n      firstName\n      createdAt\n      roles\n      username\n    }\n  }\n"): (typeof documents)["\n  query meAdmin {\n    meAdmin {\n      id\n      lastName\n      firstName\n      createdAt\n      roles\n      username\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation updateCustomerActionAdminInputs(\n    $updateCustomerActionAdminInputs: UpdateCustomerActionAdminInputsGQL!\n  ) {\n    updateCustomerActionAdmin(\n      updateCustomerActionAdminInputs: $updateCustomerActionAdminInputs\n    ) {\n      id\n      text\n      customerId\n      userId\n    }\n  }\n"): (typeof documents)["\n  mutation updateCustomerActionAdminInputs(\n    $updateCustomerActionAdminInputs: UpdateCustomerActionAdminInputsGQL!\n  ) {\n    updateCustomerActionAdmin(\n      updateCustomerActionAdminInputs: $updateCustomerActionAdminInputs\n    ) {\n      id\n      text\n      customerId\n      userId\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation addFileToCustomerActionAdmin(\n    $addFileToCustomerActionAdmin: AddFileToCustomerActionAdminInputsGQL!\n  ) {\n    addFileToCustomerActionAdmin(\n      addFileToCustomerActionAdmin: $addFileToCustomerActionAdmin\n    ) {\n      id\n    }\n  }\n"): (typeof documents)["\n  mutation addFileToCustomerActionAdmin(\n    $addFileToCustomerActionAdmin: AddFileToCustomerActionAdminInputsGQL!\n  ) {\n    addFileToCustomerActionAdmin(\n      addFileToCustomerActionAdmin: $addFileToCustomerActionAdmin\n    ) {\n      id\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query getCustomerActionByIdAdmin($customerActionId: String!) {\n    getCustomerActionByIdAdmin(customerActionId: $customerActionId) {\n      id\n      text\n      customerId\n      customer {\n        email\n        jobTitle\n        phone\n        officePhone\n      }\n      userId\n      user {\n        id\n        firstName\n        username\n      }\n      fileUses {\n        id\n        file {\n          id\n          filename\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query getCustomerActionByIdAdmin($customerActionId: String!) {\n    getCustomerActionByIdAdmin(customerActionId: $customerActionId) {\n      id\n      text\n      customerId\n      customer {\n        email\n        jobTitle\n        phone\n        officePhone\n      }\n      userId\n      user {\n        id\n        firstName\n        username\n      }\n      fileUses {\n        id\n        file {\n          id\n          filename\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query getCustomerActionsAdmin(\n    $getCustomerActionsAdminArgs: GetCustomerActionsAdminArgsGQL!\n    $paginationArgs: PaginationArgsGQL!\n  ) {\n    getCustomerActionsAdmin(\n      getCustomerActionsAdminArgs: $getCustomerActionsAdminArgs\n      paginationArgs: $paginationArgs\n    ) {\n      pageInfo {\n        totalEdges\n        edgeCount\n        edgesPerPage\n        currentPage\n        totalPages\n      }\n      edges {\n        id\n        text\n        customer {\n          email\n          jobTitle\n          phone\n          officePhone\n        }\n        userId\n        user {\n          id\n          firstName\n          lastName\n          username\n        }\n        fileUses {\n          id\n          file {\n            id\n            filename\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query getCustomerActionsAdmin(\n    $getCustomerActionsAdminArgs: GetCustomerActionsAdminArgsGQL!\n    $paginationArgs: PaginationArgsGQL!\n  ) {\n    getCustomerActionsAdmin(\n      getCustomerActionsAdminArgs: $getCustomerActionsAdminArgs\n      paginationArgs: $paginationArgs\n    ) {\n      pageInfo {\n        totalEdges\n        edgeCount\n        edgesPerPage\n        currentPage\n        totalPages\n      }\n      edges {\n        id\n        text\n        customer {\n          email\n          jobTitle\n          phone\n          officePhone\n        }\n        userId\n        user {\n          id\n          firstName\n          lastName\n          username\n        }\n        fileUses {\n          id\n          file {\n            id\n            filename\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation createCustomerActionAdminInputs(\n    $createCustomerActionAdminInputs: CreateCustomerActionAdminInputsGQL!\n  ) {\n    createCustomerActionAdmin(\n      createCustomerActionAdminInputs: $createCustomerActionAdminInputs\n    ) {\n      id\n      text\n      customerId\n      userId\n    }\n  }\n"): (typeof documents)["\n  mutation createCustomerActionAdminInputs(\n    $createCustomerActionAdminInputs: CreateCustomerActionAdminInputsGQL!\n  ) {\n    createCustomerActionAdmin(\n      createCustomerActionAdminInputs: $createCustomerActionAdminInputs\n    ) {\n      id\n      text\n      customerId\n      userId\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query getCustomerByIdAdmin($customerId: String!) {\n    getCustomerByIdAdmin(customerId: $customerId) {\n      id\n      firstName\n      lastName\n      email\n      jobTitle\n      phone\n      officePhone\n      isActive\n      cityId\n      city {\n        name\n        id\n        province {\n          id\n          name\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query getCustomerByIdAdmin($customerId: String!) {\n    getCustomerByIdAdmin(customerId: $customerId) {\n      id\n      firstName\n      lastName\n      email\n      jobTitle\n      phone\n      officePhone\n      isActive\n      cityId\n      city {\n        name\n        id\n        province {\n          id\n          name\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query getCustomersAdmin(\n    $getCustomersAdminArgs: GetCustomersAdminArgsGQL!\n    $paginationArgs: PaginationArgsGQL!\n  ) {\n    getCustomersAdmin(\n      getCustomersAdminArgs: $getCustomersAdminArgs\n      paginationArgs: $paginationArgs\n    ) {\n      pageInfo {\n        totalEdges\n        edgeCount\n        edgesPerPage\n        currentPage\n        totalPages\n      }\n      edges {\n        id\n        firstName\n        lastName\n        email\n        jobTitle\n        phone\n        officePhone\n        isActive\n        cityId\n        city {\n          id\n          name\n          province {\n            name\n            id\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query getCustomersAdmin(\n    $getCustomersAdminArgs: GetCustomersAdminArgsGQL!\n    $paginationArgs: PaginationArgsGQL!\n  ) {\n    getCustomersAdmin(\n      getCustomersAdminArgs: $getCustomersAdminArgs\n      paginationArgs: $paginationArgs\n    ) {\n      pageInfo {\n        totalEdges\n        edgeCount\n        edgesPerPage\n        currentPage\n        totalPages\n      }\n      edges {\n        id\n        firstName\n        lastName\n        email\n        jobTitle\n        phone\n        officePhone\n        isActive\n        cityId\n        city {\n          id\n          name\n          province {\n            name\n            id\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query loginAdmin($loginAdminInputs: LoginAdminInputsGQL!) {\n    loginAdmin(loginAdminInputs: $loginAdminInputs) {\n      id\n      lastName\n      firstName\n      createdAt\n      roles\n      username\n    }\n  }\n"): (typeof documents)["\n  query loginAdmin($loginAdminInputs: LoginAdminInputsGQL!) {\n    loginAdmin(loginAdminInputs: $loginAdminInputs) {\n      id\n      lastName\n      firstName\n      createdAt\n      roles\n      username\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query logoutAdmin {\n    logoutAdmin {\n      id\n    }\n  }\n"): (typeof documents)["\n  query logoutAdmin {\n    logoutAdmin {\n      id\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query getMessageByIdAdmin($messageId: String!) {\n    getMessageByIdAdmin(messageId: $messageId) {\n      id\n      text\n      count\n      createdAt\n      updatedAt\n      deletedAt\n      isActive\n      isSubmited\n      userId\n      user {\n        id\n        username\n        firstName\n        lastName\n      }\n      customerMessages {\n        id\n        customer {\n          id\n          email\n          jobTitle\n          firstName\n          lastName\n          email\n          phone\n          officePhone\n          isActive\n          city {\n            id\n            name\n            province {\n              id\n              name\n            }\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query getMessageByIdAdmin($messageId: String!) {\n    getMessageByIdAdmin(messageId: $messageId) {\n      id\n      text\n      count\n      createdAt\n      updatedAt\n      deletedAt\n      isActive\n      isSubmited\n      userId\n      user {\n        id\n        username\n        firstName\n        lastName\n      }\n      customerMessages {\n        id\n        customer {\n          id\n          email\n          jobTitle\n          firstName\n          lastName\n          email\n          phone\n          officePhone\n          isActive\n          city {\n            id\n            name\n            province {\n              id\n              name\n            }\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query getMessagesAdmin(\n    $getMessagesAdminArgs: GetMessagesAdminArgsGQL!\n    $paginationArgs: PaginationArgsGQL!\n  ) {\n    getMessagesAdmin(\n      getMessagesAdminArgs: $getMessagesAdminArgs\n      paginationArgs: $paginationArgs\n    ) {\n      pageInfo {\n        totalEdges\n        edgeCount\n        edgesPerPage\n        currentPage\n        totalPages\n      }\n      edges {\n        id\n        text\n        count\n        createdAt\n        updatedAt\n        deletedAt\n        isActive\n        isSubmited\n        userId\n        user {\n          id\n          username\n          firstName\n          lastName\n        }\n        customerMessages {\n          id\n          customer {\n            id\n            email\n            jobTitle\n            firstName\n            lastName\n            email\n            phone\n            officePhone\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query getMessagesAdmin(\n    $getMessagesAdminArgs: GetMessagesAdminArgsGQL!\n    $paginationArgs: PaginationArgsGQL!\n  ) {\n    getMessagesAdmin(\n      getMessagesAdminArgs: $getMessagesAdminArgs\n      paginationArgs: $paginationArgs\n    ) {\n      pageInfo {\n        totalEdges\n        edgeCount\n        edgesPerPage\n        currentPage\n        totalPages\n      }\n      edges {\n        id\n        text\n        count\n        createdAt\n        updatedAt\n        deletedAt\n        isActive\n        isSubmited\n        userId\n        user {\n          id\n          username\n          firstName\n          lastName\n        }\n        customerMessages {\n          id\n          customer {\n            id\n            email\n            jobTitle\n            firstName\n            lastName\n            email\n            phone\n            officePhone\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation updateProducerActionAdminInputs(\n    $updateProducerActionAdminInputs: UpdateProducerActionAdminInputsGQL!\n  ) {\n    updateProducerActionAdmin(\n      updateProducerActionAdminInputs: $updateProducerActionAdminInputs\n    ) {\n      id\n      text\n      producerId\n      userId\n    }\n  }\n"): (typeof documents)["\n  mutation updateProducerActionAdminInputs(\n    $updateProducerActionAdminInputs: UpdateProducerActionAdminInputsGQL!\n  ) {\n    updateProducerActionAdmin(\n      updateProducerActionAdminInputs: $updateProducerActionAdminInputs\n    ) {\n      id\n      text\n      producerId\n      userId\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation addFileToProducerActionAdmin(\n    $addFileToProducerActionAdmin: AddFileToProducerActionAdminInputsGQL!\n  ) {\n    addFileToProducerActionAdmin(\n      addFileToProducerActionAdmin: $addFileToProducerActionAdmin\n    ) {\n      id\n    }\n  }\n"): (typeof documents)["\n  mutation addFileToProducerActionAdmin(\n    $addFileToProducerActionAdmin: AddFileToProducerActionAdminInputsGQL!\n  ) {\n    addFileToProducerActionAdmin(\n      addFileToProducerActionAdmin: $addFileToProducerActionAdmin\n    ) {\n      id\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query getProducerActionByIdAdmin($producerActionId: String!) {\n    getProducerActionByIdAdmin(producerActionId: $producerActionId) {\n      id\n      text\n      producerId\n      producer {\n        id\n        name\n        phone\n        email\n        description\n        address\n        isActive\n      }\n      userId\n      user {\n        id\n        firstName\n        username\n        email\n        lastName\n      }\n      fileUses {\n        id\n        file {\n          id\n          filename\n          path\n          isUsed\n          size\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query getProducerActionByIdAdmin($producerActionId: String!) {\n    getProducerActionByIdAdmin(producerActionId: $producerActionId) {\n      id\n      text\n      producerId\n      producer {\n        id\n        name\n        phone\n        email\n        description\n        address\n        isActive\n      }\n      userId\n      user {\n        id\n        firstName\n        username\n        email\n        lastName\n      }\n      fileUses {\n        id\n        file {\n          id\n          filename\n          path\n          isUsed\n          size\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query getProducerActionsAdmin(\n    $getProducerActionsAdminArgs: GetProducerActionsAdminArgsGQL!\n    $paginationArgs: PaginationArgsGQL!\n  ) {\n    getProducerActionsAdmin(\n      getProducerActionsAdminArgs: $getProducerActionsAdminArgs\n      paginationArgs: $paginationArgs\n    ) {\n      pageInfo {\n        totalEdges\n        edgeCount\n        edgesPerPage\n        currentPage\n        totalPages\n      }\n      edges {\n        id\n        text\n        producer {\n          id\n          name\n          phone\n          email\n          description\n          address\n        }\n        userId\n        user {\n          id\n          firstName\n          username\n          lastName\n        }\n        fileUses {\n          id\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query getProducerActionsAdmin(\n    $getProducerActionsAdminArgs: GetProducerActionsAdminArgsGQL!\n    $paginationArgs: PaginationArgsGQL!\n  ) {\n    getProducerActionsAdmin(\n      getProducerActionsAdminArgs: $getProducerActionsAdminArgs\n      paginationArgs: $paginationArgs\n    ) {\n      pageInfo {\n        totalEdges\n        edgeCount\n        edgesPerPage\n        currentPage\n        totalPages\n      }\n      edges {\n        id\n        text\n        producer {\n          id\n          name\n          phone\n          email\n          description\n          address\n        }\n        userId\n        user {\n          id\n          firstName\n          username\n          lastName\n        }\n        fileUses {\n          id\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query getProducerAgentByIdAdmin($producerAgentId: String!) {\n    getProducerAgentByIdAdmin(producerAgentId: $producerAgentId) {\n      id\n      createdAt\n      firstName\n      lastName\n      email\n      phone\n      description\n      isActive\n      producer {\n        id\n        name\n        phone\n        email\n        cityId\n        city {\n          id\n          name\n          province {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query getProducerAgentByIdAdmin($producerAgentId: String!) {\n    getProducerAgentByIdAdmin(producerAgentId: $producerAgentId) {\n      id\n      createdAt\n      firstName\n      lastName\n      email\n      phone\n      description\n      isActive\n      producer {\n        id\n        name\n        phone\n        email\n        cityId\n        city {\n          id\n          name\n          province {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query getProducerAgentsAdmin(\n    $getProducerAgentsAdminArgs: GetProducerAgentsAdminArgsGQL!\n    $paginationArgs: PaginationArgsGQL!\n  ) {\n    getProducerAgentsAdmin(\n      getProducerAgentsAdminArgs: $getProducerAgentsAdminArgs\n      paginationArgs: $paginationArgs\n    ) {\n      pageInfo {\n        totalEdges\n        edgeCount\n        edgesPerPage\n        currentPage\n        totalPages\n      }\n      edges {\n        id\n        createdAt\n        firstName\n        lastName\n        email\n        phone\n        description\n        isActive\n        producer {\n          id\n          name\n          phone\n          email\n          cityId\n          city {\n            id\n            name\n            province {\n              id\n              name\n            }\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query getProducerAgentsAdmin(\n    $getProducerAgentsAdminArgs: GetProducerAgentsAdminArgsGQL!\n    $paginationArgs: PaginationArgsGQL!\n  ) {\n    getProducerAgentsAdmin(\n      getProducerAgentsAdminArgs: $getProducerAgentsAdminArgs\n      paginationArgs: $paginationArgs\n    ) {\n      pageInfo {\n        totalEdges\n        edgeCount\n        edgesPerPage\n        currentPage\n        totalPages\n      }\n      edges {\n        id\n        createdAt\n        firstName\n        lastName\n        email\n        phone\n        description\n        isActive\n        producer {\n          id\n          name\n          phone\n          email\n          cityId\n          city {\n            id\n            name\n            province {\n              id\n              name\n            }\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation createProducerActionAdminInputs(\n    $createProducerActionAdminInputs: CreateProducerActionAdminInputsGQL!\n  ) {\n    createProducerActionAdmin(\n      createProducerActionAdminInputs: $createProducerActionAdminInputs\n    ) {\n      id\n      text\n      producerId\n      userId\n    }\n  }\n"): (typeof documents)["\n  mutation createProducerActionAdminInputs(\n    $createProducerActionAdminInputs: CreateProducerActionAdminInputsGQL!\n  ) {\n    createProducerActionAdmin(\n      createProducerActionAdminInputs: $createProducerActionAdminInputs\n    ) {\n      id\n      text\n      producerId\n      userId\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query getProducerByIdAdmin($producerId: String!) {\n    getProducerByIdAdmin(producerId: $producerId) {\n      id\n      name\n      phone\n      email\n      description\n      address\n      isActive\n      cityId\n      city {\n        id\n        name\n        province {\n          name\n          id\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query getProducerByIdAdmin($producerId: String!) {\n    getProducerByIdAdmin(producerId: $producerId) {\n      id\n      name\n      phone\n      email\n      description\n      address\n      isActive\n      cityId\n      city {\n        id\n        name\n        province {\n          name\n          id\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query getProducersAdmin(\n    $getProducersAdminArgs: GetProducersAdminArgsGQL!\n    $paginationArgs: PaginationArgsGQL!\n  ) {\n    getProducersAdmin(\n      getProducersAdminArgs: $getProducersAdminArgs\n      paginationArgs: $paginationArgs\n    ) {\n      pageInfo {\n        totalEdges\n        edgeCount\n        edgesPerPage\n        currentPage\n        totalPages\n      }\n      edges {\n        id\n        email\n        name\n        description\n        address\n        phone\n        isActive\n        cityId\n        city {\n          id\n          name\n          province {\n            name\n            id\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query getProducersAdmin(\n    $getProducersAdminArgs: GetProducersAdminArgsGQL!\n    $paginationArgs: PaginationArgsGQL!\n  ) {\n    getProducersAdmin(\n      getProducersAdminArgs: $getProducersAdminArgs\n      paginationArgs: $paginationArgs\n    ) {\n      pageInfo {\n        totalEdges\n        edgeCount\n        edgesPerPage\n        currentPage\n        totalPages\n      }\n      edges {\n        id\n        email\n        name\n        description\n        address\n        phone\n        isActive\n        cityId\n        city {\n          id\n          name\n          province {\n            name\n            id\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query getProductByIdAdmin($productId: String!) {\n    getProductByIdAdmin(productId: $productId) {\n      id\n      name\n      slug\n      isActive\n      text\n      productColors {\n        id\n        colorId\n        color {\n          id\n          value\n          name\n        }\n      }\n      productReviews {\n        id\n        reviewer\n        text\n      }\n      productCategories {\n        id\n        categoryId\n        category {\n          id\n          name\n        }\n      }\n      productProperties {\n        id\n        value\n        property {\n          id\n          name\n          unit\n          isActive\n        }\n      }\n      fileUses {\n        file {\n          id\n          filename\n          path\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query getProductByIdAdmin($productId: String!) {\n    getProductByIdAdmin(productId: $productId) {\n      id\n      name\n      slug\n      isActive\n      text\n      productColors {\n        id\n        colorId\n        color {\n          id\n          value\n          name\n        }\n      }\n      productReviews {\n        id\n        reviewer\n        text\n      }\n      productCategories {\n        id\n        categoryId\n        category {\n          id\n          name\n        }\n      }\n      productProperties {\n        id\n        value\n        property {\n          id\n          name\n          unit\n          isActive\n        }\n      }\n      fileUses {\n        file {\n          id\n          filename\n          path\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query getProductsAdmin(\n    $getProductsAdminArgs: GetProductsAdminArgsGQL!\n    $paginationArgs: PaginationArgsGQL!\n  ) {\n    getProductsAdmin(\n      getProductsAdminArgs: $getProductsAdminArgs\n      paginationArgs: $paginationArgs\n    ) {\n      pageInfo {\n        totalEdges\n        edgeCount\n        edgesPerPage\n        currentPage\n        totalPages\n      }\n      edges {\n        slug\n        id\n        name\n        isActive\n        createdAt\n        updatedAt\n        deletedAt\n        text\n        productProperties {\n          id\n          value\n          property {\n            name\n            unit\n          }\n        }\n        fileUses {\n          id\n          status\n          type\n          isPublic\n          file {\n            filename\n            size\n            id\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query getProductsAdmin(\n    $getProductsAdminArgs: GetProductsAdminArgsGQL!\n    $paginationArgs: PaginationArgsGQL!\n  ) {\n    getProductsAdmin(\n      getProductsAdminArgs: $getProductsAdminArgs\n      paginationArgs: $paginationArgs\n    ) {\n      pageInfo {\n        totalEdges\n        edgeCount\n        edgesPerPage\n        currentPage\n        totalPages\n      }\n      edges {\n        slug\n        id\n        name\n        isActive\n        createdAt\n        updatedAt\n        deletedAt\n        text\n        productProperties {\n          id\n          value\n          property {\n            name\n            unit\n          }\n        }\n        fileUses {\n          id\n          status\n          type\n          isPublic\n          file {\n            filename\n            size\n            id\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation updateTransporterActionAdminInputs(\n    $updateTransporterActionAdminInputs: UpdateTransporterActionAdminInputsGQL!\n  ) {\n    updateTransporterActionAdmin(\n      updateTransporterActionAdminInputs: $updateTransporterActionAdminInputs\n    ) {\n      id\n      text\n      transporterId\n      userId\n    }\n  }\n"): (typeof documents)["\n  mutation updateTransporterActionAdminInputs(\n    $updateTransporterActionAdminInputs: UpdateTransporterActionAdminInputsGQL!\n  ) {\n    updateTransporterActionAdmin(\n      updateTransporterActionAdminInputs: $updateTransporterActionAdminInputs\n    ) {\n      id\n      text\n      transporterId\n      userId\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation addFileToTransporterActionAdmin(\n    $addFileToTransporterActionAdmin: AddFileToTransporterActionAdminInputsGQL!\n  ) {\n    addFileToTransporterActionAdmin(\n      addFileToTransporterActionAdmin: $addFileToTransporterActionAdmin\n    ) {\n      id\n    }\n  }\n"): (typeof documents)["\n  mutation addFileToTransporterActionAdmin(\n    $addFileToTransporterActionAdmin: AddFileToTransporterActionAdminInputsGQL!\n  ) {\n    addFileToTransporterActionAdmin(\n      addFileToTransporterActionAdmin: $addFileToTransporterActionAdmin\n    ) {\n      id\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query getTransporterActionByIdAdmin($transporterActionId: String!) {\n    getTransporterActionByIdAdmin(transporterActionId: $transporterActionId) {\n      id\n      text\n      transporterId\n      transporter {\n        id\n        name\n        phone\n        email\n        description\n        address\n        isActive\n      }\n      userId\n      user {\n        id\n        firstName\n        username\n        email\n        lastName\n      }\n      fileUses {\n        id\n        file {\n          id\n          filename\n          path\n          isUsed\n          size\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query getTransporterActionByIdAdmin($transporterActionId: String!) {\n    getTransporterActionByIdAdmin(transporterActionId: $transporterActionId) {\n      id\n      text\n      transporterId\n      transporter {\n        id\n        name\n        phone\n        email\n        description\n        address\n        isActive\n      }\n      userId\n      user {\n        id\n        firstName\n        username\n        email\n        lastName\n      }\n      fileUses {\n        id\n        file {\n          id\n          filename\n          path\n          isUsed\n          size\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query getTransporterActionsAdmin(\n    $getTransporterActionsAdminArgs: GetTransporterActionsAdminArgsGQL!\n    $paginationArgs: PaginationArgsGQL!\n  ) {\n    getTransporterActionsAdmin(\n      getTransporterActionsAdminArgs: $getTransporterActionsAdminArgs\n      paginationArgs: $paginationArgs\n    ) {\n      pageInfo {\n        totalEdges\n        edgeCount\n        edgesPerPage\n        currentPage\n        totalPages\n      }\n      edges {\n        id\n        text\n        transporter {\n          id\n          name\n          phone\n          email\n          description\n          address\n        }\n        userId\n        user {\n          id\n          firstName\n          username\n          lastName\n        }\n        fileUses {\n          id\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query getTransporterActionsAdmin(\n    $getTransporterActionsAdminArgs: GetTransporterActionsAdminArgsGQL!\n    $paginationArgs: PaginationArgsGQL!\n  ) {\n    getTransporterActionsAdmin(\n      getTransporterActionsAdminArgs: $getTransporterActionsAdminArgs\n      paginationArgs: $paginationArgs\n    ) {\n      pageInfo {\n        totalEdges\n        edgeCount\n        edgesPerPage\n        currentPage\n        totalPages\n      }\n      edges {\n        id\n        text\n        transporter {\n          id\n          name\n          phone\n          email\n          description\n          address\n        }\n        userId\n        user {\n          id\n          firstName\n          username\n          lastName\n        }\n        fileUses {\n          id\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query getTransporterAgentByIdAdmin($transporterAgentId: String!) {\n    getTransporterAgentByIdAdmin(transporterAgentId: $transporterAgentId) {\n      id\n      createdAt\n      firstName\n      lastName\n      email\n      phone\n      description\n      isActive\n      transporter {\n        id\n        name\n        phone\n        email\n        cityId\n        city {\n          id\n          name\n          province {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query getTransporterAgentByIdAdmin($transporterAgentId: String!) {\n    getTransporterAgentByIdAdmin(transporterAgentId: $transporterAgentId) {\n      id\n      createdAt\n      firstName\n      lastName\n      email\n      phone\n      description\n      isActive\n      transporter {\n        id\n        name\n        phone\n        email\n        cityId\n        city {\n          id\n          name\n          province {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query getTransporterAgentsAdmin(\n    $getTransporterAgentsAdminArgs: GetTransporterAgentsAdminArgsGQL!\n    $paginationArgs: PaginationArgsGQL!\n  ) {\n    getTransporterAgentsAdmin(\n      getTransporterAgentsAdminArgs: $getTransporterAgentsAdminArgs\n      paginationArgs: $paginationArgs\n    ) {\n      pageInfo {\n        totalEdges\n        edgeCount\n        edgesPerPage\n        currentPage\n        totalPages\n      }\n      edges {\n        id\n        createdAt\n        firstName\n        lastName\n        email\n        phone\n        description\n        isActive\n        transporter {\n          id\n          name\n          phone\n          email\n          cityId\n          city {\n            id\n            name\n            province {\n              id\n              name\n            }\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query getTransporterAgentsAdmin(\n    $getTransporterAgentsAdminArgs: GetTransporterAgentsAdminArgsGQL!\n    $paginationArgs: PaginationArgsGQL!\n  ) {\n    getTransporterAgentsAdmin(\n      getTransporterAgentsAdminArgs: $getTransporterAgentsAdminArgs\n      paginationArgs: $paginationArgs\n    ) {\n      pageInfo {\n        totalEdges\n        edgeCount\n        edgesPerPage\n        currentPage\n        totalPages\n      }\n      edges {\n        id\n        createdAt\n        firstName\n        lastName\n        email\n        phone\n        description\n        isActive\n        transporter {\n          id\n          name\n          phone\n          email\n          cityId\n          city {\n            id\n            name\n            province {\n              id\n              name\n            }\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation createTransporterActionAdminInputs(\n    $createTransporterActionAdminInputs: CreateTransporterActionAdminInputsGQL!\n  ) {\n    createTransporterActionAdmin(\n      createTransporterActionAdminInputs: $createTransporterActionAdminInputs\n    ) {\n      id\n      text\n      transporterId\n      userId\n    }\n  }\n"): (typeof documents)["\n  mutation createTransporterActionAdminInputs(\n    $createTransporterActionAdminInputs: CreateTransporterActionAdminInputsGQL!\n  ) {\n    createTransporterActionAdmin(\n      createTransporterActionAdminInputs: $createTransporterActionAdminInputs\n    ) {\n      id\n      text\n      transporterId\n      userId\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query getTransporterByIdAdmin($transporterId: String!) {\n    getTransporterByIdAdmin(transporterId: $transporterId) {\n      id\n      name\n      phone\n      email\n      description\n      address\n      isActive\n      cityId\n      city {\n        id\n        name\n        province {\n          name\n          id\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query getTransporterByIdAdmin($transporterId: String!) {\n    getTransporterByIdAdmin(transporterId: $transporterId) {\n      id\n      name\n      phone\n      email\n      description\n      address\n      isActive\n      cityId\n      city {\n        id\n        name\n        province {\n          name\n          id\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query getTransportersAdmin(\n    $getTransportersAdminArgs: GetTransportersAdminArgsGQL!\n    $paginationArgs: PaginationArgsGQL!\n  ) {\n    getTransportersAdmin(\n      getTransportersAdminArgs: $getTransportersAdminArgs\n      paginationArgs: $paginationArgs\n    ) {\n      pageInfo {\n        totalEdges\n        edgeCount\n        edgesPerPage\n        currentPage\n        totalPages\n      }\n      edges {\n        id\n        email\n        name\n        description\n        address\n        phone\n        isActive\n        cityId\n        city {\n          id\n          name\n          province {\n            name\n            id\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query getTransportersAdmin(\n    $getTransportersAdminArgs: GetTransportersAdminArgsGQL!\n    $paginationArgs: PaginationArgsGQL!\n  ) {\n    getTransportersAdmin(\n      getTransportersAdminArgs: $getTransportersAdminArgs\n      paginationArgs: $paginationArgs\n    ) {\n      pageInfo {\n        totalEdges\n        edgeCount\n        edgesPerPage\n        currentPage\n        totalPages\n      }\n      edges {\n        id\n        email\n        name\n        description\n        address\n        phone\n        isActive\n        cityId\n        city {\n          id\n          name\n          province {\n            name\n            id\n          }\n        }\n      }\n    }\n  }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;