import { MigrationInterface, QueryRunner } from "typeorm";

export class colors1677347894449 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    for (const color of colors) {
      await queryRunner.manager.query(
        `INSERT INTO public.color(name, value) VALUES ('${color.name}', '${color.value}');`
      );
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    for (const color of colors) {
      await queryRunner.manager.query(
        `DELETE FROM public.color WHERE value='${color.value}';`
      );
    }
  }
}

const colors = [
  {
    name: "INDIANRED",
    value: "CD5C5C",
    rgb: "RGB(205, 92, 92)",
    families: ["red", "brown"],
  },
  {
    name: "LIGHTCORAL",
    value: "F08080",
    rgb: "RGB(240, 128, 128)",
    families: ["red", "pink", "coral", "light"],
  },
  {
    name: "SALMON",
    value: "FA8072",
    rgb: "RGB(250, 128, 114)",
    families: ["red", "pink", "orange", "salmon"],
  },
  {
    name: "DARKSALMON",
    value: "E9967A",
    rgb: "RGB(233, 150, 122)",
    families: ["red", "pink", "orange", "salmon", "dark"],
  },
  {
    name: "LIGHTSALMON",
    value: "FFA07A",
    rgb: "RGB(255, 160, 122)",
    families: ["red", "pink", "orange", "salmon", "light"],
  },
  {
    name: "CRIMSON",
    value: "DC143C",
    rgb: "RGB(220, 20, 60)",
    families: ["red"],
  },
  {
    name: "RED",
    value: "FF0000",
    rgb: "RGB(255, 0, 0)",
    families: ["red"],
  },
  {
    name: "DARKRED",
    value: "8B0000",
    rgb: "RGB(139, 0, 0)",
    families: ["red", "dark"],
  },
  {
    name: "PINK",
    value: "FFC0CB",
    rgb: "RGB(255, 192, 203)",
    families: ["pink"],
  },
  {
    name: "LIGHTPINK",
    value: "FFB6C1",
    rgb: "RGB(255, 182, 193)",
    families: ["pink", "light"],
  },
  {
    name: "HOTPINK",
    value: "FF69B4",
    rgb: "RGB(255, 105, 180)",
    families: ["pink", "hot"],
  },
  {
    name: "DEEPPINK",
    value: "FF1493",
    rgb: "RGB(255, 20, 147)",
    families: ["pink", "deep"],
  },
  {
    name: "MEDIUMVIOLETRED",
    value: "C71585",
    rgb: "RGB(199, 21, 133)",
    families: ["pink", "purple", "violet", "medium"],
  },
  {
    name: "PALEVIOLETRED",
    value: "DB7093",
    rgb: "RGB(219, 112, 147)",
    families: ["pink", "pale", "violet"],
  },
  {
    name: "CORAL",
    value: "FF7F50",
    rgb: "RGB(255, 127, 80)",
    families: ["orange", "coral"],
  },
  {
    name: "TOMATO",
    value: "FF6347",
    rgb: "RGB(255, 99, 71",
    families: ["orange", "red"],
  },
  {
    name: "ORANGERED",
    value: "FF4500",
    rgb: "RGB(255, 69, 0)",
    families: ["orange", "red"],
  },
  {
    name: "DARKORANGE",
    value: "FF8C00",
    rgb: "RGB(255, 140, 0)",
    families: ["orange", "dark"],
  },
  {
    name: "ORANGE",
    value: "FFA500",
    rgb: "RGB(255, 165, 0)",
    families: ["orange"],
  },
  {
    name: "GOLD",
    value: "FFD700",
    rgb: "RGB(255, 215, 0)",
    families: ["yellow"],
  },
  {
    name: "YELLOW",
    value: "FFFF00",
    rgb: "RGB(255, 255, 0)",
    families: ["yellow"],
  },
  {
    name: "LIGHTYELLOW",
    value: "FFFFE0",
    rgb: "RGB(255, 255, 224)",
    families: ["yellow", "light"],
  },
  {
    name: "LEMONCHIFFON",
    value: "FFFACD",
    rgb: "RGB(255, 250, 205)",
    families: ["yellow", "lemon"],
  },
  {
    name: "LIGHTGOLDENRODYELLOW",
    value: "FAFAD2",
    rgb: "RGB(250, 250, 210)",
    families: ["yellow", "light", "goldenrod", "tan"],
  },
  {
    name: "PAPAYAWHIP",
    value: "FFEFD5",
    rgb: "RGB(255, 239, 213)",
    families: ["pink", "tan"],
  },
  {
    name: "MOCCASIN",
    value: "FFE4B5",
    rgb: "RGB(255, 228, 181)",
    families: ["pink", "tan"],
  },
  {
    name: "PEACHPUFF",
    value: "FFDAB9",
    rgb: "RGB(255, 218, 185)",
    families: ["pink", "orange", "peach"],
  },
  {
    name: "PALEGOLDENROD",
    value: "EEE8AA",
    rgb: "RGB(238, 232, 170)",
    families: ["yellow", "tan", "pale", "goldenrod"],
  },
  {
    name: "KHAKI",
    value: "F0E68C",
    rgb: "RGB(240, 230, 140)",
    families: ["yellow", "tan", "khaki"],
  },
  {
    name: "DARKKHAKI",
    value: "BDB76B",
    rgb: "RGB(189, 183, 107)",
    families: ["yellow", "tan", "khaki", "dark"],
  },
  {
    name: "LAVENDER",
    value: "E6E6FA",
    rgb: "RGB(230, 230, 250)",
    families: ["purple"],
  },
  {
    name: "THISTLE",
    value: "D8BFD8",
    rgb: "RGB(216, 191, 216)",
    families: ["purple"],
  },
  {
    name: "PLUM",
    value: "DDA0DD",
    rgb: "RGB(221, 160, 221)",
    families: ["purple"],
  },
  {
    name: "VIOLET",
    value: "EE82EE",
    rgb: "RGB(238, 130, 238)",
    families: ["purple", "violet", "pink"],
  },
  {
    name: "ORCHID",
    value: "DA70D6",
    rgb: "RGB(218, 112, 214)",
    families: ["purple", "orchid"],
  },
  {
    name: "FUCHSIA",
    value: "FF00FF",
    rgb: "RGB(255, 0, 255)",
    families: ["purple", "pink"],
  },
  {
    name: "MEDIUMORCHID",
    value: "BA55D3",
    rgb: "RGB(186, 85, 211)",
    families: ["purple", "orchid", "medium"],
  },
  {
    name: "MEDIUMPURPLE",
    value: "9370DB",
    rgb: "RGB(147, 112, 219)",
    families: ["purple", "medium"],
  },
  {
    name: "REBECCAPURPLE",
    value: "663399",
    rgb: "RGB(102, 51, 153)",
    families: ["purple", "blue"],
  },
  {
    name: "BLUEVIOLET",
    value: "8A2BE2",
    rgb: "RGB(138, 43, 226)",
    families: ["purple", "blue", "violet"],
  },
  {
    name: "DARKVIOLET",
    value: "9400D3",
    rgb: "RGB(148, 0, 211)",
    families: ["purple", "dark", "violet"],
  },
  {
    name: "DARKORCHID",
    value: "9932CC",
    rgb: "RGB(153, 50, 204)",
    families: ["purple", "dark", "orchid"],
  },
  {
    name: "DARKMAGENTA",
    value: "8B008B",
    rgb: "RGB(139, 0, 139)",
    families: ["purple", "dark", "magenta"],
  },
  {
    name: "PURPLE",
    value: "800080",
    rgb: "RGB(128, 0, 128)",
    families: ["purple"],
  },
  {
    name: "INDIGO",
    value: "4B0082",
    rgb: "RGB(75, 0, 130)",
    families: ["purple", "blue"],
  },
  {
    name: "SLATEBLUE",
    value: "6A5ACD",
    rgb: "RGB(106, 90, 205)",
    families: ["purple", "blue", "slate"],
  },
  {
    name: "DARKSLATEBLUE",
    value: "483D8B",
    rgb: "RGB(72, 61, 139)",
    families: ["purple", "blue", "slate", "dark"],
  },
  {
    name: "MEDIUMSLATEBLUE",
    value: "7B68EE",
    rgb: "RGB(123, 104, 238)",
    families: ["purple", "blue", "slate", "medium"],
  },
  {
    name: "GREENYELLOW",
    value: "ADFF2F",
    rgb: "RGB(173, 255, 47)",
    families: ["green", "yellow"],
  },
  {
    name: "CHARTREUSE",
    value: "7FFF00",
    rgb: "RGB(127, 255, 0)",
    families: ["green"],
  },
  {
    name: "LAWNGREEN",
    value: "7CFC00",
    rgb: "RGB(124, 252, 0)",
    families: ["green"],
  },
  {
    name: "LIME",
    value: "00FF00",
    rgb: "RGB(0, 255, 0)",
    families: ["green"],
  },
  {
    name: "LIMEGREEN",
    value: "32CD32",
    rgb: "RGB(50, 205, 50)",
    families: ["green"],
  },
  {
    name: "PALEGREEN",
    value: "98FB98",
    rgb: "RGB(152, 251, 152)",
    families: ["green", "pale"],
  },
  {
    name: "LIGHTGREEN",
    value: "90EE90",
    rgb: "RGB(144, 238, 144)",
    families: ["green", "light"],
  },
  {
    name: "MEDIUMSPRINGGREEN",
    value: "00FA9A",
    rgb: "RGB(0, 250, 154)",
    families: ["green", "medium", "spring"],
  },
  {
    name: "SPRINGGREEN",
    value: "00FF7F",
    rgb: "RGB(0, 255, 127)",
    families: ["green", "spring"],
  },
  {
    name: "MEDIUMSEAGREEN",
    value: "3CB371",
    rgb: "RGB(60, 179, 113)",
    families: ["green", "sea", "medium"],
  },
  {
    name: "SEAGREEN",
    value: "2E8B57",
    rgb: "RGB(46, 139, 87)",
    families: ["green", "sea"],
  },
  {
    name: "FORESTGREEN",
    value: "228B22",
    rgb: "RGB(34, 139, 34)",
    families: ["green", "forest"],
  },
  {
    name: "GREEN",
    value: "008000",
    rgb: "RGB(0, 128, 0)",
    families: ["green"],
  },
  {
    name: "DARKGREEN",
    value: "006400",
    rgb: "RGB(0, 100, 0)",
    families: ["green", "dark"],
  },
  {
    name: "YELLOWGREEN",
    value: "9ACD32",
    rgb: "RGB(154, 205, 50)",
    families: ["green", "yellow"],
  },
  {
    name: "OLIVEDRAB",
    value: "6B8E23",
    rgb: "RGB(107, 142, 35)",
    families: ["green", "olive"],
  },
  {
    name: "DARKOLIVEGREEN",
    value: "556B2F",
    rgb: "RGB(85, 107, 47)",
    families: ["green", "olive", "dark"],
  },
  {
    name: "MEDIUMAQUAMARINE",
    value: "66CDAA",
    rgb: "RGB(102, 205, 170)",
    families: ["green", "blue", "aquamarine", "medium"],
  },
  {
    name: "DARKSEAGREEN",
    value: "8FBC8B",
    rgb: "RGB(143, 188, 139)",
    families: ["green", "sea", "dark"],
  },
  {
    name: "LIGHTSEAGREEN",
    value: "20B2AA",
    rgb: "RGB(32, 178, 170)",
    families: ["green", "blue", "sea", "light"],
  },
  {
    name: "DARKCYAN",
    value: "008B8B",
    rgb: "RGB(0, 139, 139)",
    families: ["green", "blue", "cyan", "dark"],
  },
  {
    name: "TEAL",
    value: "008080",
    rgb: "RGB(0, 128, 128)",
    families: ["green", "blue"],
  },
  {
    name: "CYAN",
    value: "00FFFF",
    rgb: "RGB(0, 255, 255)",
    families: ["blue", "cyan"],
  },
  {
    name: "LIGHTCYAN",
    value: "E0FFFF",
    rgb: "RGB(224, 255, 255)",
    families: ["blue", "cyan", "light"],
  },
  {
    name: "PALETURQUOISE",
    value: "AFEEEE",
    rgb: "RGB(175, 238, 238)",
    families: ["blue", "turquoise", "pale"],
  },
  {
    name: "AQUAMARINE",
    value: "7FFFD4",
    rgb: "RGB(127, 255, 212)",
    families: ["blue", "aquamarine"],
  },
  {
    name: "TURQUOISE",
    value: "40E0D0",
    rgb: "RGB(64, 224, 208)",
    families: ["blue", "turquoise"],
  },
  {
    name: "MEDIUMTURQUOISE",
    value: "48D1CC",
    rgb: "RGB(72, 209, 204)",
    families: ["blue", "turquoise", "medium"],
  },
  {
    name: "DARKTURQUOISE",
    value: "00CED1",
    rgb: "RGB(0, 206, 209)",
    families: ["blue", "turquoise", "dark"],
  },
  {
    name: "CADETBLUE",
    value: "5F9EA0",
    rgb: "RGB(95, 158, 160)",
    families: ["blue", "gray"],
  },
  {
    name: "STEELBLUE",
    value: "4682B4",
    rgb: "RGB(70, 130, 180)",
    families: ["blue", "steel"],
  },
  {
    name: "LIGHTSTEELBLUE",
    value: "B0C4DE",
    rgb: "RGB(176, 196, 222)",
    families: ["blue", "steel", "light"],
  },
  {
    name: "POWDERBLUE",
    value: "B0E0E6",
    rgb: "RGB(176, 224, 230)",
    families: ["blue"],
  },
  {
    name: "LIGHTBLUE",
    value: "ADD8E6",
    rgb: "RGB(173, 216, 230)",
    families: ["blue", "light"],
  },
  {
    name: "SKYBLUE",
    value: "87CEEB",
    rgb: "RGB(135, 206, 235)",
    families: ["blue", "sky"],
  },
  {
    name: "LIGHTSKYBLUE",
    value: "87CEFA",
    rgb: "RGB(135, 206, 250)",
    families: ["blue", "sky", "light"],
  },
  {
    name: "DEEPSKYBLUE",
    value: "00BFFF",
    rgb: "RGB(0, 191, 255)",
    families: ["blue", "sky", "deep"],
  },
  {
    name: "DODGERBLUE",
    value: "1E90FF",
    rgb: "RGB(30, 144, 255)",
    families: ["blue"],
  },
  {
    name: "CORNFLOWERBLUE",
    value: "6495ED",
    rgb: "RGB(100, 149, 237)",
    families: ["blue"],
  },
  {
    name: "ROYALBLUE",
    value: "4169E1",
    rgb: "RGB(65, 105, 225)",
    families: ["blue"],
  },
  {
    name: "BLUE",
    value: "0000FF",
    rgb: "RGB(0, 0, 255)",
    families: ["blue"],
  },
  {
    name: "MEDIUMBLUE",
    value: "0000CD",
    rgb: "RGB(0, 0, 205)",
    families: ["blue", "medium"],
  },
  {
    name: "NAVY",
    value: "00008B",
    rgb: "RGB(0, 0, 128)",
    families: ["blue", "dark"],
  },
  {
    name: "MIDNIGHTBLUE",
    value: "191970",
    rgb: "RGB(25, 25, 112))",
    families: ["blue", "dark"],
  },
  {
    name: "CORNSILK",
    value: "FFF8DC",
    rgb: "RGB(255, 248, 220)",
    families: ["brown", "tan"],
  },
  {
    name: "BLANCHEDALMOND",
    value: "FFEBCD",
    rgb: "RGB(255, 235, 205)",
    families: ["brown", "tan"],
  },
  {
    name: "BISQUE",
    value: "FFE4C4",
    rgb: "RGB(255, 228, 196)",
    families: ["brown", "tan"],
  },
  {
    name: "NAVAJOWHITE",
    value: "FFDEAD",
    rgb: "RGB(255, 222, 173)",
    families: ["brown", "tan"],
  },
  {
    name: "WHEAT",
    value: "F5DEB3",
    rgb: "RGB(245, 222, 179)",
    families: ["brown", "tan"],
  },
  {
    name: "BURLYWOOD",
    value: "DEB887",
    rgb: "RGB(222, 184, 135)",
    families: ["brown", "tan"],
  },
  {
    name: "TAN",
    value: "D2B48C",
    rgb: "RGB(210, 180, 140)",
    families: ["brown", "tan"],
  },
  {
    name: "ROSYBROWN",
    value: "BC8F8F",
    rgb: "RGB(188, 143, 143)",
    families: ["brown", "tan"],
  },
  {
    name: "SANDYBROWN",
    value: "F4A460",
    rgb: "RGB(244, 164, 96)",
    families: ["brown", "orange"],
  },
  {
    name: "GOLDENROD",
    value: "DAA520",
    rgb: "RGB(218, 165, 32)",
    families: ["brown", "goldenrod", "orange"],
  },
  {
    name: "DARKGOLDENROD",
    value: "B8860B",
    rgb: "RGB(184, 134, 11)",
    families: ["brown", "orange", "goldenrod", "dark"],
  },
  {
    name: "PERU",
    value: "CD853F",
    rgb: "RGB(205, 133, 63)",
    families: ["brown", "orange"],
  },
  {
    name: "CHOCOLATE",
    value: "D2691E",
    rgb: "RGB(210, 105, 30)",
    families: ["brown", "orange"],
  },
  {
    name: "SADDLEBROWN",
    value: "8B4513",
    rgb: "RGB(139, 69, 19)",
    families: ["brown"],
  },
  {
    name: "SIENNA",
    value: "A0522D",
    rgb: "RGB(160, 82, 45)",
    families: ["brown"],
  },
  {
    name: "BROWN",
    value: "A52A2A",
    rgb: "RGB(165, 42, 42)",
    families: ["brown", "red"],
  },
  {
    name: "MAROON",
    value: "800000",
    rgb: "RGB(128, 0, 0)",
    families: ["brown", "red"],
  },
  {
    name: "WHITE",
    value: "FFFFFF",
    rgb: "RGB(255, 255, 255)",
    families: ["white"],
  },
  {
    name: "SNOW",
    value: "FFFAFA",
    rgb: "RGB(255, 250, 250)",
    families: ["white"],
  },
  {
    name: "HONEYDEW",
    value: "F0FFF0",
    rgb: "RGB(240, 255, 240)",
    families: ["white"],
  },
  {
    name: "MINTCREAM",
    value: "F5FFFA",
    rgb: "RGB(245, 255, 250)",
    families: ["white"],
  },
  {
    name: "AZURE",
    value: "F0FFFF",
    rgb: "RGB(240, 255, 255)",
    families: ["white"],
  },
  {
    name: "ALICEBLUE",
    value: "F0F8FF",
    rgb: "RGB(240, 248, 255)",
    families: ["white"],
  },
  {
    name: "GHOSTWHITE",
    value: "F8F8FF",
    rgb: "RGB(248, 248, 255)",
    families: ["white"],
  },
  {
    name: "WHITESMOKE",
    value: "F5F5F5",
    rgb: "RGB(245, 245, 245)",
    families: ["white"],
  },
  {
    name: "SEASHELL",
    value: "FFF5EE",
    rgb: "RGB(255, 245, 238)",
    families: ["white", "pink"],
  },
  {
    name: "BEIGE",
    value: "F5F5DC",
    rgb: "RGB(245, 245, 220)",
    families: ["white", "tan"],
  },
  {
    name: "FLORALWHITE",
    value: "FDF5E6",
    rgb: "RGB(253, 245, 230)",
    families: ["white", "tan"],
  },
  {
    name: "IVORY",
    value: "FFFFF0",
    rgb: "RGB(255, 255, 240)",
    families: ["white", "tan"],
  },
  {
    name: "ANTIQUEWHITE",
    value: "FAEBD7",
    rgb: "RGB(250, 235, 215)",
    families: ["white", "tan"],
  },
  {
    name: "LINEN",
    value: "FAF0E6",
    rgb: "RGB(250, 240, 230)",
    families: ["white", "tan"],
  },
  {
    name: "LAVENDERBLUSH",
    value: "FFF0F5",
    rgb: "RGB(255, 240, 245)",
    families: ["white", "lavender", "pink"],
  },
  {
    name: "MISTYROSE",
    value: "FFE4E1",
    rgb: "RGB(255, 228, 225)",
    families: ["white", "pink"],
  },
  {
    name: "GAINSBORO",
    value: "DCDCDC",
    rgb: "RGB(220, 220, 220)",
    families: ["gray"],
  },
  {
    name: "LIGHTGRAY",
    value: "D3D3D3",
    rgb: "RGB(211, 211, 211)",
    families: ["gray", "light"],
  },
  {
    name: "SILVER",
    value: "C0C0C0",
    rgb: "RGB(192, 192, 192)",
    families: ["gray"],
  },
  {
    name: "DARKGRAY",
    value: "A9A9A9",
    rgb: "RGB(169, 169, 169)",
    families: ["gray", "dark"],
  },
  {
    name: "GRAY",
    value: "808080",
    rgb: "RGB(128, 128, 128)",
    families: ["gray"],
  },
  {
    name: "DIMGRAY",
    value: "696969",
    rgb: "RGB(105, 105, 105)",
    families: ["gray"],
  },
  {
    name: "LIGHTSLATEGRAY",
    value: "778899",
    rgb: "RGB(119, 136, 153)",
    families: ["gray", "light", "slate"],
  },
  {
    name: "SLATEGRAY",
    value: "708090",
    rgb: "RGB(112, 128, 144)",
    families: ["gray", "slate"],
  },
  {
    name: "DARKSLATEGRAY",
    value: "2F4F4F",
    rgb: "RGB(47, 79, 79)",
    families: ["gray", "slate", "dark"],
  },
  {
    name: "BLACK",
    value: "000000",
    rgb: "RGB(0, 0, 0)",
    families: ["black"],
  },
];
